/*
	PlotLEDPeakDrift.C
	Clint Wiseman, USC/Majorana
	August 2015.

	Takes input from a series of calibration tables generated by builtVetoCal.
	Makes TGraphs of the LED peak positions of the 32 veto panels, with an 
	error bar equal to 1-sigma of the LED peak's Gaussian distribution.

	Usage: 
	root[0] .X PlotLEDPeakDrift.C
*/

#include <vector>

struct PeakInfo {
	Int_t panel;
	Float_t mean;
	Float_t meanErr;
	Float_t sigma;
	Float_t sigmaErr;
	Float_t chi2_NDF;

	PeakInfo() {
		panel=0; mean=0; meanErr=0;
		sigma=0; sigmaErr=0; chi2_NDF=0;
	}
};

void PlotLEDPeakDrift() {

	const Int_t n = 5; // number of files to scan

	string Input[n];
	Input[0] = "./output/M1BG_Range1_CalibrationTable.txt";
	Input[1] = "./output/M1BG_Range2_CalibrationTable.txt";
	Input[2] = "./output/M1BG_Range3_CalibrationTable.txt";
	Input[3] = "./output/M1BG_Range4_CalibrationTable.txt";
	Input[4] = "./output/M1BG_Range5_CalibrationTable.txt";

	// store all peak info in one giant table
	PeakInfo peaks[n][32];

	ifstream InputList;
	for (int i = 0; i<n; i++) {
		InputList.open(Input[i].c_str());
		cout << "Opened " << Input[i] << endl;

		PeakInfo pk; // temp peak
	
		while(!InputList.eof()){

			InputList >> pk.panel >> pk.mean >> pk.meanErr >> pk.sigma >> pk.sigmaErr >> pk.chi2_NDF;

			//printf("%i  %.0f  %.0f  %.0f  %.0f  %.0f\n",pk.panel,pk.mean,pk.meanErr,pk.sigma,pk.sigmaErr,pk.chi2_NDF);

			peaks[i][pk.panel].panel = pk.panel;
			peaks[i][pk.panel].mean = pk.mean;
			peaks[i][pk.panel].meanErr = pk.meanErr;
			peaks[i][pk.panel].sigma = pk.sigma;
			peaks[i][pk.panel].sigmaErr = pk.sigmaErr;
			peaks[i][pk.panel].chi2_NDF = pk.chi2_NDF;

	    }
	    InputList.close();
	}

	// pull out variables
	vector<Float_t> xaxis[32];
	vector<Float_t> xerr[32];
	vector<Float_t> mean[32];
	vector<Float_t> meanErr[32];
	vector<Float_t> sigma[32];
	vector<Float_t> sigmaErr[32];
	vector<Float_t> chi2_NDF[32];

	// i == 0 for all files, i == 1 to skip first file
	for (int i = 0; i < n; i++) { 
		for (int j = 0; j < 32; j++) {
			//cout << peaks[i][j].mean << "  "  << peaks[i][j].sigma << endl;
			xaxis[j].push_back((Float_t)i);
			xerr[j].push_back(0);
			mean[j].push_back(peaks[i][j].mean);
			meanErr[j].push_back(peaks[i][j].meanErr);
			sigma[j].push_back(peaks[i][j].sigma);
			sigmaErr[j].push_back(peaks[i][j].sigmaErr);
			chi2_NDF[j].push_back(peaks[i][j].chi2_NDF);
		}
	}


	TCanvas *c1 = new TCanvas("c1","Bob Ross's Canvas",600,600);
	c1->SetGrid();

	TH1F *hr = c1->DrawFrame(0,0,5,4200);
	hr->SetXTitle("Range Number");
	hr->SetYTitle("qdc");
	hr->GetYaxis()->SetTitleOffset(1.55);
	hr->SetTitle("LED Peak Drift, all panels");
	TGraphErrors *g[32];
	//TLegend *legend = new TLegend(0.9,0.3,1.0,1.0);
	TLegend *legend = new TLegend(0.8,0.58,0.9,0.9);
	Char_t name[200];
	for (int i = 0; i < 32; i++){ 

		//if (i >=0 && i <= 11) { // bottom
		//if (i == 17 || i == 18 || i == 20 || i == 21) { // top
		//if (i == 15 || i == 16 || i == 19 || i == 23 ) { // north
		//if (i == 24 || i == 25 || i == 26 || i == 27 ) { // south
		//if (i == 28 || i == 29 || i == 30 || i == 31 ) { // east
		//if (i == 12 || i == 13 || i == 14 || i == 22 ) { // west 
		g[i] = new TGraphErrors(xaxis[i].size(),&(xaxis[i][0]), &(mean[i][0]),&(xerr[i][0]), &(sigma[i][0]));
		g[i]->SetLineColor(color(i));
		g[i]->SetMarkerColor(color(i));
		g[i]->SetMarkerStyle(20);
		g[i]->SetLineWidth(2);	// want to make error bars thicker
		g[i]->Draw("LP");
		sprintf(name,"panel %i",i);
		legend->AddEntry(g[i],name,"lep");
		//}
	}
	legend->Draw();

}

// ROOT color wheel: 
// https://root.cern.ch/root/html/TColor.html
int color(int i){

	if (i == 0) return kRed;  // L-bot 1
	if (i == 1) return kRed-2;  
	if (i == 2) return kRed-4;
	if (i == 3) return kRed-6;
	if (i == 4) return kRed-8;
	if (i == 5) return kRed-10;  // L-bot 6

	if (i == 6) return kBlue;  // U-bot 1
	if (i == 7) return kBlue+2;
	if (i == 8) return kBlue+4;
	if (i == 9) return kBlue+6;
	if (i == 10) return kBlue+8;
	if (i == 11) return kBlue+10; // U-bot 6

	if (i == 17) return kAzure; // Top 1
	if (i == 18) return kAzure+3; // Top 2
	if (i == 20) return kAzure+6; // Top 3
	if (i == 21) return kAzure+9; // Top 4

	if (i == 15) return kMagenta; // North 1
	if (i == 16) return kMagenta+2; // North 2
	if (i == 19) return kMagenta-5; // North 3
	if (i == 23) return kMagenta-10; // North 4

	if (i == 24) return kGreen; // South 1
	if (i == 25) return kGreen+2; // South 2
	if (i == 26) return kGreen+4; // South 3
	if (i == 27) return kGreen-5; // South 4
	
	if (i == 12) return kSpring; // West 1
	if (i == 13) return kSpring-7; // West 2
	if (i == 14) return kSpring+2; // West 3
	if (i == 22) return kSpring+3; // West 4
	
	if (i == 28) return kYellow+2; // East 1
	if (i == 29) return kYellow+4; // East 2
	if (i == 30) return kYellow-6; // East 3
	if (i == 31) return kYellow-3; // East 4
}